image: node:latest

stages: # List of stages for jobs, and their order of execution
  - build
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - cd client
  - npm ci --cache .npm --prefer-offline

build-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "We're not deploying yet"
