image: node:latest

stages: # List of stages for jobs, and their order of execution
  - pre
  - build
  - test
  - deploy

after_script:
  - cd ..

build-client-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."

deploy-client-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "We're not deploying yet"
