image: node:latest

stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

after_script:
  - cd ..

build-server-job: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - cd rest-api
    - npm ci --cache .npm --prefer-offline
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - cd rest-api
    - npm ci --cache .npm --prefer-offline
    - npm run test:cov
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "All test passed"
    - echo "test coverage"
  artifacts:
    when: always
    reports:
      junit:
        - ./rest-api/junit.xml

deploy-job: # This job runs in the deploy stage.
  stage: deploy # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "We're not deploying yet"
